WFX_DEF_VER = "5.6"

WFX_ADDONS_PATH = WFXGetPath().."scripts\\"

FW_NORMAL               = 400
FW_EXTRABOLD            = 800

WFX_MODULEID_UNKNOWN    = 0x1
WFX_MODULEID_HWIDBYPASS = 0x2
WFX_MODULEID_RESERVED1  = 0x4
WFX_MODULEID_RESERVED2  = 0x8

WFX_EVENTID_DRAW       = 0
WFX_EVENTID_PROJECTILEDIR  = 1
WFX_EVENTID_ACTIVATEAPP  = 2
WFX_EVENTID_KEYDOWN      = 3
WFX_EVENTID_KEYUP        = 4
WFX_EVENTID_LBUTTON_DOWN = 5
WFX_EVENTID_LBUTTON_UP   = 6
WFX_EVENTID_RBUTTON_DOWN = 7
WFX_EVENTID_RBUTTON_UP   = 8
WFX_EVENTID_VAC          = 9
WFX_EVENTID_RESERVED_EVENT1 = 10
WFX_EVENTID_RESERVED_EVENT2 = 11
WFX_EVENTID_WHEEL_DOWN   = 12
WFX_EVENTID_WHEEL_UP     = 13
WFX_EVENTID_MOUSEMOVE    = 14
WFX_EVENTID_ACTION       = 15
WFX_EVENTID_EXECUTE_GAMECOMMAND = 16
WFX_EVENTID_RECV_DATA    = 17
WFX_EVENTID_SEND_DATA    = 18
WFX_EVENTID_CHAT_MESSAGE = 19
WFX_EVENTID_MAIN = 20

WFX_FUNCTION_ID_CHECK     = -1
WFX_FUNCTION_ID_NORECOIL  =  0
WFX_FUNCTION_ID_NOSPREAD  =  1
WFX_FUNCTION_ID_VAC       =  2
WFX_FUNCTION_ID_ANTI_FLASH_GRENADE = 3
WFX_FUNCTION_ID_UNLIMITED_RUN      = 4
WFX_FUNCTION_ID_UNLIMITED_SLIDE    = 5

WEAPON_ID_1ST = 0
WEAPON_ID_2ND = 1
WEAPON_ID_3RD = 2

WEAPON_HEAVY   = WEAPON_ID_1ST
WEAPON_MEDIUM  = WEAPON_ID_2ND
WEAPON_SMALL   = WEAPON_ID_3RD